name: amnesty_env
channels:
  - conda-forge
dependencies:
  - anyio=3.4.0
  - argon2-cffi=21.1.0
  - asttokens=2.0.5
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - blosc=1.21.0
  - boost-cpp=1.74.0
  - branca=0.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - charset-normalizer=2.0.9
  - click=8.0.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - cryptography=36.0.1
  - curl=7.80.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - executing=0.8.2
  - expat=2.4.2
  - fiona=1.8.20
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.28.5
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.4.0
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - geos=3.10.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icecream=2.1.1
  - icu=69.1
  - idna=3.1
  - importlib-metadata=4.10.0
  - importlib_resources=5.4.0
  - ipykernel=6.6.0
  - ipython=7.30.1
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9d
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.3.2
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyter_server=1.13.1
  - jupyterlab=3.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.9.0
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libdap4=3.20.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.4.0
  - libglib=2.70.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=14.1
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.0.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munch=2.5.0
  - munkres=1.1.4
  - nbclassic=0.3.4
  - nbclient=0.5.9
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - networkx=2.6.3
  - notebook=6.4.6
  - nspr=4.32
  - nss=3.73
  - numpy=1.21.5
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - pixman=0.40.0
  - plotnine=0.8.0
  - poppler=21.11.0
  - poppler-data=0.4.11
  - postgresql=14.1
  - proj=8.2.0
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyproj=3.3.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.1
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2021.3
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.26.0
  - rtree=0.9.7
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=60.0.3
  - shapely=1.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.37.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tiledb=2.5.3
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - tzcode=2021e
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2021.11.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
